main : Test.cpp Factorial.cpp Factorial.h Sum.cpp Sum.h Partitioning.cpp Partitioning.h Change.cpp Change.h Defs.h
	g++ Test.cpp Factorial.cpp Sum.cpp Partitioning.cpp Change.cpp -I ../cute/ -I ../boost/ -std=c++11 -g -o main
