1 : 1.cpp
	g++ 1.cpp -g -std=c++11 -o main

2 : 2.cpp
	g++ 2.cpp -g -std=c++11 -o main

3 : 3.cpp
	g++ 3.cpp -g -std=c++11 -o main

4 : 4.cpp
	g++ 4.cpp -g -std=c++11 -o main

5 : 5.cpp
	g++ 5.cpp -g -std=c++11 -o main

7 : 7.cpp
	g++ 7.cpp -g -std=c++11 -o main